return {}
-- is not working yet
-- return {
--   "mfussenegger/nvim-dap",
--   dependencies = {
--     "rcarriga/nvim-dap-ui",
--     "theHamsta/nvim-dap-virtual-text",
--   },
--   config = function()
--     local dap = require("dap")
--     require("dapui").setup()
--     vim.keymap.set("n", "<leader>dt", dap.toggle_breakpoint, { desc = "Toggle breakpoint" })
--     vim.keymap.set("n", "<leader>dc", dap.continue, { desc = "Continue" })
--     dap.adapters.firefox = {
--       type = "executable",
--       command = "node",
--       args = { os.getenv("HOME") .. "/home/ham/Documents/debugger/vscode-firefox-debug/dist/adapter.bundle.js" },
--     }
--     dap.configurations.typescript = {
--       {
--         name = "Debug with Firefox",
--         type = "firefox",
--         request = "launch",
--         reAttach = true,
--         url = "http://localhost:3000",
--         webRoot = "${workspaceFolder}",
--         firefoxExecutable = "/usr/bin/firefox",
--       },
--     }
--   end,
-- }
